train:
  hidden_layer: 128
  activation : 'softmax'
  lr : 0.001
  model_output_path: "../models/trained_model.h5"
  epoch: 20
  host: '128.0.1.1'
  port: 8080


infer:
  next_words: 5
  model_path: "../models/trained_model.h5"
  max_sequence_len: 40