train:
  hidden_layer: 64
  activation : 'softmax'
  lr : 0.001
  model_output_path: "../models/trained_model.h5"
  epoch: 4


infer:
  next_words: 5
  model_path: "../models/trained_model.h5"
  max_sequence_len: 40